"""Application constants and UI text for VINAFCO Manifest Cleaner.

This module contains all application-level constants including
version info, UI text translations (Vietnamese/English), and color scheme.
"""

# --- Application Info ---
APP_TITLE = "Manifest Cleaner"
APP_VERSION = "3.0.0"
APP_AUTHOR_VI = "Cảng Tiền-Tân Thuận"
APP_AUTHOR_EN = "Tien-Tan Thuan Port"

# --- Default Settings ---
DEFAULT_LANGUAGE = "vi"

# --- Color Scheme ---
COLORS = {
    "primary": "#1565C0",
    "primary_dark": "#0D47A1",
    "primary_light": "#E3F2FD",
    "success": "#2E7D32",
    "success_light": "#E8F5E9",
    "warning": "#F57C00",
    "error": "#C62828",
    "bg_light": "#FAFAFA",
    "bg_card": "#FFFFFF",
    "text_primary": "#212121",
    "text_secondary": "#757575",
    "text_muted": "#9E9E9E",
    "border": "#E0E0E0",
    "dropzone": "#E8EAF6",
    "dropzone_active": "#C5CAE9",
}

# --- UI Text (Bilingual Support) ---
UI_TEXT = {
    "vi": {
        "lang_code": "vi",
        "lang_name": "Tiếng Việt",
        "lang_flag": "🇻🇳",
        "app_subtitle": "Xử lý & Chuẩn hóa dữ liệu Manifest VINAFCO",
        "btn_choose_file": "📂 Chọn file (Ctrl+O)",
        "btn_batch": "📚 Batch (Ctrl+B)",
        "btn_processing": "⏳ Đang xử lý...",
        "status_waiting": "Sẵn sàng",
        "status_reading": "Đang đọc file...",
        "status_extracting": "Đang trích xuất...",
        "status_processing": "Đang xử lý...",
        "status_building": "Đang tạo bảng...",
        "status_saving": "Đang lưu...",
        "status_complete": "✅ Hoàn thành!",
        "status_error": "❌ Lỗi",
        "status_cancelled": "⚠️ Đã hủy",
        "dialog_choose_file": "Chọn file Cargo Manifest VINAFCO",
        "dialog_batch": "Chọn nhiều file để xử lý",
        "dialog_save_file": "Lưu file kết quả",
        "footer_version": "Phiên bản",
        "footer_author": "Phát triển bởi",
        "msg_success_title": "Thành công",
        "msg_success": "Đã xử lý và lưu file thành công!",
        "msg_error_title": "Lỗi",
        "msg_error_read": "Không thể đọc file Excel",
        "msg_error_general": "Lỗi không mong muốn",
        "msg_file_not_found": "Không tìm thấy file",
        "msg_cancelled_title": "Đã hủy",
        "msg_cancelled": "Thao tác lưu file đã bị hủy.",
        "msg_no_data_title": "Không có dữ liệu",
        "msg_no_data": "Không tìm thấy dữ liệu container.",
        "tooltip_lang": "Chuyển ngôn ngữ",
        "recent_files": "📂 Gần đây:",
        "recent_toggle_show": "▼ Hiện ({count})",
        "recent_toggle_hide": "▲ Ẩn",
        "no_recent": "Chưa có file nào",
        "help_title": "Phím tắt",
        "help_content": "Ctrl+O: Mở file\nCtrl+B: Batch processing\nCtrl+S: Lưu\nF1: Trợ giúp\nEsc: Đóng dialog",
        "preview_title": "📊 Xem trước dữ liệu",
        "filter_label": "🔍 Lọc:",
        "btn_save_excel": "💾 Lưu Excel",
        "btn_save_csv": "📄 Lưu CSV",
        "btn_close": "❌ Đóng",
        "stats_total": "Tổng",
        "stats_shown": "Hiển thị",
        "stats_full": "Full",
        "stats_empty": "Empty",
        "menu_settings": "⚙️ Cài đặt",
        "menu_language": "🌐 Ngôn ngữ",
        "menu_sound": "🔊 Âm thanh",
        "menu_batch": "📚 Xử lý nhiều file (Ctrl+B)",
        "menu_help": "❓ Trợ giúp (F1)",
        "menu_about": "ℹ️ Giới thiệu",
        "about_title": "Giới thiệu",
        "about_content": "VINAFCO Manifest Cleaner\nPhiên bản {version}\n\nCông cụ xử lý và chuẩn hóa dữ liệu\nCargo Manifest của hãng tàu VINAFCO.\n\nPhát triển bởi: {author}",
        "batch_title": "Xử lý hàng loạt",
        "batch_select": "Chọn files để xử lý",
        "batch_progress": "Đang xử lý {current}/{total}...",
        "batch_complete": "Hoàn thành {success}/{total} files",
        "batch_error": "Lỗi: {count} files",
    },
    "en": {
        "lang_code": "en",
        "lang_name": "English",
        "lang_flag": "🇬🇧",
        "app_subtitle": "Process & Format VINAFCO Manifest Data",
        "btn_choose_file": "📂 Open (Ctrl+O)",
        "btn_batch": "📚 Batch (Ctrl+B)",
        "btn_processing": "⏳ Processing...",
        "status_waiting": "Ready",
        "status_reading": "Reading file...",
        "status_extracting": "Extracting...",
        "status_processing": "Processing...",
        "status_building": "Building table...",
        "status_saving": "Saving...",
        "status_complete": "✅ Done!",
        "status_error": "❌ Error",
        "status_cancelled": "⚠️ Cancelled",
        "dialog_choose_file": "Select VINAFCO Cargo Manifest File",
        "dialog_batch": "Select multiple files to process",
        "dialog_save_file": "Save Result File",
        "footer_version": "Version",
        "footer_author": "Developed by",
        "msg_success_title": "Success",
        "msg_success": "File processed and saved successfully!",
        "msg_error_title": "Error",
        "msg_error_read": "Cannot read Excel file",
        "msg_error_general": "Unexpected error",
        "msg_file_not_found": "File not found",
        "msg_cancelled_title": "Cancelled",
        "msg_cancelled": "Save operation cancelled.",
        "msg_no_data_title": "No Data",
        "msg_no_data": "No container data found.",
        "tooltip_lang": "Switch language",
        "recent_files": "📂 Recent:",
        "recent_toggle_show": "▼ Show ({count})",
        "recent_toggle_hide": "▲ Hide",
        "no_recent": "No recent files",
        "help_title": "Keyboard Shortcuts",
        "help_content": "Ctrl+O: Open file\nCtrl+B: Batch processing\nCtrl+S: Save\nF1: Help\nEsc: Close dialog",
        "preview_title": "📊 Data Preview",
        "filter_label": "🔍 Filter:",
        "btn_save_excel": "💾 Save Excel",
        "btn_save_csv": "📄 Save CSV",
        "btn_close": "❌ Close",
        "stats_total": "Total",
        "stats_shown": "Shown",
        "stats_full": "Full",
        "stats_empty": "Empty",
        "menu_settings": "⚙️ Settings",
        "menu_language": "🌐 Language",
        "menu_sound": "🔊 Sound",
        "menu_batch": "📚 Batch Process (Ctrl+B)",
        "menu_help": "❓ Help (F1)",
        "menu_about": "ℹ️ About",
        "about_title": "About",
        "about_content": "VINAFCO Manifest Cleaner\nVersion {version}\n\nA tool for processing and formatting\nVINAFCO shipping line Cargo Manifest data.\n\nDeveloped by: {author}",
        "batch_title": "Batch Processing",
        "batch_select": "Select files to process",
        "batch_progress": "Processing {current}/{total}...",
        "batch_complete": "Completed {success}/{total} files",
        "batch_error": "Errors: {count} files",
    },
}

# --- Excel Output Column Names ---
OUTPUT_COLUMNS = {
    "vi": {
        "stt": "STT",
        "quantity": "Số lượng",
        "bl_no": "Số BL",
        "container_no": "Số Container",
        "operator": "Hãng khai thác",
        "size_type": "Kích cỡ",
        "iso_size": "Kích cỡ VTOS",
        "fe_status": "F/E",
        "weight": "TL hàng",
        "seal_no": "Số niêm chì",
        "seal_no_1": "Số niêm chì 1",
        "consignee": "Chủ hàng",
        "goods": "Hàng hóa",
        "cargo_type": "Loại hàng",
    },
    "en": {
        "stt": "No.",
        "quantity": "Qty",
        "bl_no": "BL No.",
        "container_no": "Container No.",
        "operator": "Operator",
        "size_type": "Size/Type",
        "iso_size": "ISO Size",
        "fe_status": "F/E",
        "weight": "Weight (T)",
        "seal_no": "Seal No.",
        "seal_no_1": "Seal No. 1",
        "consignee": "Consignee",
        "goods": "Description",
        "cargo_type": "Cargo Type",
    },
}
